name: My_Worlds
version: ${project.version}
build: ${project.build.number}
api-version: 1.13
authors: [KamikazePlatypus, mg_1999, Friwi, bergerkiller, lenis0012, timstans, bubba1234119]
softdepend: [BKCommonLib, Multiverse-Core, PlaceholderAPI]
loadbefore: [CMI, dynmap, Citizens, MobArena, RegionForSale, CreativeGates, HeroStronghold, CustomNPCs]
classdepend: [BetterPortals, MythicDungeons]
metrics: true

bstats:
    enabled: true
    plugin-id: 18763

main: com.bergerkiller.bukkit.mw.Preloader
preloader:
    main: com.bergerkiller.bukkit.mw.MyWorlds
    hastebinServer: https://paste.traincarts.net
    depend:
        BKCommonLib: https://www.spigotmc.org/resources/bkcommonlib.39590/

commands:
    world:
        description: Commands to manage your worlds
        aliases: [myworlds, mw, worlds]
        usage: |
            Use /help world [subcommand] for more information
            /world info - Show world information
            /world list - List all worlds
            /world load - Load an existing world
            /world unload - Unload a loaded world
            /world save - Save a loaded world
            /world create - Create a new world
            /world listgenerators - List world generators
            /world setspawn - Set the spawn point of a world
            /world spawn - Teleport to world spawn
            /world time - Set the time of a world
            /world weather - Set the weather of a world
            /world setnetherportal - Set nether portal destination
            /world setendportal - Set ender portal destination
            /world gamemode - Set the game mode of a world
            /world hunger - Toggle hunger on or off
            /world difficulty - Set the difficulty of a world
            /world pvp - Toggle PVP mode on/off
            /world allowspawn - Allow mobs to spawn
            /world denyspawn - Deny mobs from spawning
            /world inventory - Manage world inventories
            /world saving - Toggle world saving on/off
            /world spawnloaded - Toggle spawn loaded on/off
            /world forcedrespawn - Toggle forced respawn on/off
            /world bedrespawn - Toggle bed respawns on/off
            /world rememberlastpos - Toggles last-position memory on/off
            /world evacuate - Evacuate all players of a world
            /world delete - Delete a world permanently
            /world copy - Copy a world to a new name
            /world repair - Repair a world
            /world advancements - Enable/disable awarding advancements on a world
    world info:
        description: Shows detailed information of a world
        aliases: [world i]
        usage: |
            /world info
            /world info [worldname]
    world list:
        description: Lists all the worlds of the server
        usage: /world list
    world load:
        description: Loads a world
        usage: /world load [worldname]
    world unload:
        description: Unloads a world
        usage: /world unload [worldname]
    world save:
        description: Save a world
        usage: |
            /world save - Save the world you are in
            /world save [worldname] - Save worldname
            /world save [all/*] - Save all worlds
    world create:
        description: Create a new world
        usage: |
            /world create [world]_[env]:[gen]:[genarg] [seed]
            /world create NormalWorld1 SomeSeed
            /world create world2_nether MySeed
            /world create world3:Plots:64 -45245253
            /world create someworld_the_end
    world listgenerators:
        description: List all world generators
        aliases: [world generators, world gen, world listgen]
        usage: /world listgenerators
    world setspawn:
        description: Sets the spawn point of the world to your position
        usage: |
            /world setspawn - set spawn of current world
            /world setspawn [worldname] - set spawn of a world
    world spawn:
        description: Teleports you to the world spawn
        usage: |
            /world spawn - Teleport to current world spawn
            /world spawn [world] - Teleport to world spawn
    world rejoin:
        description: Teleports you or players specified to the last world and position of a world group
        usage: |
            /world rejoin [world] - Rejoins the world, or a linked world of world
    world time:
        description: Sets the time of a world
        usage: |
            /world time [time]
            /world time [time] [world]
            /world time always 12:45
            /world time night world1
    world weather:
        description: Sets the weather of a world
        usage: |
            /world weather [state]
            /world weather [state] [world]
            /world weather always raining
            /world weather sunny world2
    world gamemode:
        description: Sets the game mode of a world
        aliases: [world gm]
        usage: |
            /world gamemode [mode]
            /world gamemode [mode] [world]
            /world gamemode creative
            /world gamemode adventure
            /world gamemode spectator
            /world gamemode survival world3
    world hunger:
        description: Toggle world hunger on or off
        aliases: [world sethunger]
        usage: /world hunger [true/false]
    world difficulty:
        description: Sets the difficulty of a world
        aliases: [world diff]
        usage: |
            /world difficulty [mode]
            /world difficulty [mode] [world]
            /world difficulty hard
            /world difficulty normal world3
    world pvp:
        description: Toggles PVP on or off
        aliaes: [world togglepvp]
        usage: |
            /world pvp [on/off]
            /world pvp [on/off] [world]
    world forcedrespawn:
        description: Toggles forced world respawn on or off
        aliases: [world togglerespawn]
        usage: |
            /world forcedrespawn [on/off]
            /world forcedrespawn [on/off] [world]
    world bedrespawn:
        description: Toggles respawning at bed on or off
        aliases: [world respawnbed, world bedspawn]
        usage: |
            /world bedrespawn [on/off]
            /world bedrespawn [on/off] [world]
    world rememberlastpos:
        description: Toggles last-position memory on or off
        aliases: [world (set)rememberlast(player)pos(ition)]
        usage: |
            /world rememberlastpos [on/off]
            /world rememberlastpos [on/off] [world]
    world allowspawn:
        description: Allows certain mobs to spawn
        usage: |
            /world allowspawn [mob]
            /world allowspawn [mob] [world]
            /world allowspawn animal
            /world allowspawn creeper world2
    world denyspawn:
        description: Denies certain mobs from spawning
        usage: |
            /world denyspawn [mob]
            /world denyspawn [mob] [world]
            /world denyspawn animal
            /world denyspawn creeper world2
    world inventory:
        description: Changes world inventory settings
        aliases: [world inv]
        usage: |
            /world inventory enable
            /world inventory enable [world]
            /world inventory disable
            /world inventory disable [world]
            /world inventory split [world...]
            /world inventory merge [world1] [world...]
    world saving:
        description: Turns world saving on or off
        usage: |
            /world saving [enable/disable]
            /world saving [enable/disable] [world]
            /world saving off
            /world saving enable world2
    world spawnloaded:
        description: Toggles if the world spawn is kept loaded
        aliases: [world keepspawnloaded]
        usage: |
            /world spawnloaded [enable/disable]
            /world spawnloaded [enable/disable] [world]
    world evacuate:
        description: Clears a world of players
        aliases: [world evac]
        usage: |
            /world evacuate
            /world evacuate [world]
    world delete:
        description: Deletes an unloaded world
        usage: /world delete [world]
    world copy:
        description: Copies a world
        usage: /world copy [world_from] [world_to]
    world repair:
        description: Repairs an unloaded world
        aliases: [world rep]
        usage: /world repair [world]
    world giveportal:
        description: Gives you a stack of portal blocks for building structures
        usage: |
            /world giveportal - Give nether portal block
            /world giveportal nether - give nether portal block
            /world giveportal end - give end portal block
    world setnetherportal:
        description: Sets the nether portal destination for a world
        usage: |
            /world setnetherportal [portal/world]
            /world setnetherportal    - Reset to default
    world setendportal:
        description: Sets the ender portal destination for a world
        usage: |
            /world setendportal [portal/world]
            /world setendportal    - Reset to default
    world showcredits:
        description: Enables showing the end-game credits a second time
        usage: |
            /world showcredits - Enable for self
    world advancements:
        description: Enables or disables player getting advancements on the world
        usage: |
            /world advancements [enable/disable/silent] - Enable/disable/no chat
    tpp:
        description: Cross-world teleportation commands
        usage: /tpp [Portalname/Worldname] - Teleport to a Portal or World
